import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import Image from "next/image";
import { Background } from "@/components/Background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`antialiased relative w-screen h-screen`}
      > 
        <div className="absolute top-0">
            <Background/>
            <Header/>
            <div className="relative">
              {children}
            </div>
        </div>
      </body>
    </html>
  );
}
