import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative w-screen h-screen`}
      >
        <Image className="opacity-40" src={"/background.jpg"} fill style={{ objectFit: "cover", objectPosition: "center" }} alt=""/>
        <div className="absolute top-0">
            <Header/>
            {children}
        </div>
      </body>
    </html>
  );
}
